### ISSUE TITLE
Please document required Opensearch privileges for Camunda 8

### ISSUE THREAD

**Issue by daniel-ewing** [camunda/camunda-docs#3658] opened 2024-04-12 17:17 UTC
For example, see [Elasticsearch privileges](https://docs.camunda.io/docs/next/self-managed/concepts/elasticsearch-privileges/).

**Comment by akeller** [comment] 2024-04-12 18:49
Duplicate of https://github.com/camunda/camunda-docs/issues/3343

**Closed** 2024-04-12 18:49 UTC
